In [1]:
import numpy as np

# Create Python list
my_list = [10, 20, 30, 40, 50]

# Convert list to NumPy array
arr = np.array(my_list)

# Display array
print("NumPy Array:", arr)

# Print shape
print("Shape of array:", arr.shape)

# Print data type
print("Data type:", arr.dtype)

NumPy Array: [10 20 30 40 50]
Shape of array: (5,)
Data type: int64


In [2]:
import numpy as np

# 3x4 matrix of zeros
zeros_matrix = np.zeros((3,4))

# 2x5 matrix of ones
ones_matrix = np.ones((2,5))

print("Matrix of Zeros:")
print(zeros_matrix)
print("Shape:", zeros_matrix.shape)

print("\nMatrix of Ones:")
print(ones_matrix)
print("Shape:", ones_matrix.shape)

Matrix of Zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4)

Matrix of Ones:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Shape: (2, 5)


In [3]:
import numpy as np

# Create array from 1 to 12
arr = np.arange(1,13)

print("Original Array:")
print(arr)
print("Shape:", arr.shape)

# Reshape into 3x4 matrix
reshaped = arr.reshape(3,4)

print("\nReshaped Array (3x4):")
print(reshaped)
print("Shape:", reshaped.shape)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)

Reshaped Array (3x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


In [4]:
import numpy as np

# Generate 10 random integers between 1 and 100
arr = np.random.randint(1,100,10)

print("Random Array:", arr)

print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))
print("Mean:", np.mean(arr))
print("Sum:", np.sum(arr))

Random Array: [92 78  4 24 69 24 40 50 20 79]
Minimum: 4
Maximum: 92
Mean: 48.0
Sum: 480


In [5]:
import pandas as pd

# Dictionary of students
data = {
    "Student_Name": ["Aman", "Riya", "Kavya", "Rahul"],
    "Marks": [85, 90, 78, 88]
}

# Create DataFrame
df = pd.DataFrame(data)

print("DataFrame:")
print(df)

print("\nData Types:")
print(df.dtypes)

DataFrame:
  Student_Name  Marks
0         Aman     85
1         Riya     90
2        Kavya     78
3        Rahul     88

Data Types:
Student_Name    object
Marks            int64
dtype: object


In [6]:
import pandas as pd

# Upload CSV file
from google.colab import files
uploaded = files.upload()

# Read CSV file
df = pd.read_csv(list(uploaded.keys())[0])

print("First 5 records:")
print(df.head())

print("\nLast 5 records:")
print(df.tail())

Saving students.csv to students.csv
First 5 records:
    Name  Math  Science  English
0   Aman    85       90       88
1   Riya    78       82       80
2  Kavya    92       89       94
3  Rahul    70       75       72
4  Priya    88       91       87

Last 5 records:
    Name  Math  Science  English
5  Arjun    76       73       78
6  Sneha    95       96       94
7  Rohit    68       70       65
8   Neha    84       86       82
9  Karan    79       81       77


In [8]:
import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

df.info()
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
Rows: 891
Columns: 12
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked     

In [9]:
import pandas as pd

# Upload CSV
from google.colab import files
uploaded = files.upload()

df = pd.read_csv(list(uploaded.keys())[0])

# Statistical summary
summary = df.describe()

print("Statistical Summary:")
print(summary)

Saving students_marks.csv to students_marks.csv
Statistical Summary:
            Math    Science    English   Computer
count  10.000000  10.000000  10.000000  10.000000
mean   81.500000  83.300000  81.700000  84.400000
std     8.922506   8.590046   9.322017   9.167576
min    68.000000  70.000000  65.000000  69.000000
25%    76.500000  76.500000  77.250000  79.250000
50%    81.500000  84.000000  81.000000  84.000000
75%    87.250000  89.750000  87.750000  91.500000
max    95.000000  96.000000  94.000000  97.000000
